repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.6.0
#    hooks:
#      - id: mypy

  - repo: local
    hooks:
      - id: run-pytest
        name: Run Pytest
        entry: bash -c "pytest || true"
        language: system
        types: [python]

